source 'https://rubygems.org'

# This is separate gemfile for building docker image that has all plugins 
# for kubernetes log collection agent
# List all required gems here and install via bundler to resolve dependencies
gem "fluentd", ">=1.15.0"
gem "fluent-plugin-prometheus", ">=2.0"
gem "fluent-plugin-record-modifier", "=2.1.0"
gem "fluent-plugin-jq", "=0.5.1"
gem "oj", "~> 3.10"
gem 'multi_json', '~> 1.14'
gem 'bigdecimal', '=3.0.0'
gem 'kubeclient', '=4.9.3'
gem 'http_parser.rb', '=0.8.0'
gem 'rack', '>= 3.0.0'

gem "fluent-plugin-splunk-hec", "= 1.3.0"
gem 'fluent-plugin-kubernetes-metrics', path: 'gem/'